export const gameConfig = {
    world: {
        width: 200,
        height: 200,
        tileSize: 32, // Size of a tile in pixels (for 2D) or units (for 3D)
        roomCount: 5,
        minionsPerTown: 1,
        townWidth: 40,
        townHeight: 40
    },
    playerProgression: {
        maxLevel: 10,
        xpCurve: [4, 8, 16, 32, 64, 128, 256, 512, 1024],
        stats: {
            strength: { base: 1, max: 5 },
            agility: { base: 1, max: 5 },  // Scales up velocity
            health: { base: 3, max: 10 },
            range: { base: 1, max: 5 }
        }
    },
    enemies: [
        {
            id: "slime",
            name: "Slime",
            hp: 2,
            xp: 1,
            speed: 1.0,
            max: 15,
            toKill: 5
        },
        {
            id: "mushroom",
            name: "Mushroom",
            hp: 3,
            xp: 1,
            speed: 3.0,
            max: 20,
            toKill: 4
        },
        {
            id: "snake",
            name: "Snake",
            hp: 4,
            xp: 2,
            speed: 3.5,
            max: 20,
            toKill: 3
        },
        {
            id: "druid",
            name: "Wizard",
            hp: 5,
            xp: 3,
            speed: 1.5,
            max: 10,
            toKill: 2
        },
        {
            id: "skeleton",
            name: "Skeleton",
            hp: 6,
            xp: 6,
            speed: 2.0,
            max: 5,
            toKill: 2
        },
        {
            id: "dude",
            name: "Dude Bandit",
            hp: 7,
            xp: 4,
            speed: 6.0,
            max: 10,
            toKill: 3
        },
        {
            id: "chick",
            name: "Lady Bandit",
            hp: 7,
            xp: 4,
            speed: 6.0,
            max: 10,
            toKill: 4
        },
        {
            id: "soldier",
            name: "Undead Knight",
            hp: 20,
            xp: 15,
            speed: 8,
            max: 5,
            toKill: 1
        },
        // --- Temple enemies ---
        {
            id: "bee",
            name: "Bee",
            hp: 6,
            damage: 1,
            xp: 5,
            speed: 16.0,  // charges as fast as demon projectile
            max: 8,
            templeOnly: true
        },
        {
            id: "man_eater_flower",
            name: "Man Eater Flower",
            hp: 7,
            damage: 2,
            xp: 6,
            speed: 14.0,   // charge speed when triggered
            max: 6,
            templeOnly: true
        },
        {
            id: "arachne",
            name: "Arachne",
            hp: 10,
            damage: 2,
            xp: 10,
            speed: 3.0,   // wander speed; charges at 8.0 when triggered
            max: 5,
            templeOnly: true
        },
        {
            id: "eyeball",
            name: "Eye",
            hp: 8,
            damage: 2,
            xp: 8,
            speed: 2.5,   // wander speed
            max: 6,
            templeOnly: true
        },
        {
            id: "fire_skull",
            name: "Fire Skull",
            hp: 5,
            damage: 2,
            xp: 5,
            speed: 14.0,  // always moving at this speed
            max: 8,
            templeOnly: true
        }
    ],
    itemNameRegistry: [
        "a Sword",
        "a Shield",
        "an Axe",
        "a Bow",
        "a Staff",
        "a Potion",
        "a Scroll",
        "a Ring",
        "a Helmet",
        "Boots",
        "Gloves",
        "Shoes",
        "a Cloak",
        "an Amulet",
        "Bracers",
        "Greaves",
        "Gauntlets",
        "a Hat",
        "a Cape",
        "a Robe",
        "a Spoon",
        "a Fork",
        "a Knife",
        "a Mug",
        "a Goblet",
        "a Cup",
        "a Plate",
        "a Bowl",
        "a Laddle",
        "a Pan",
        "a Guitar",
        "a Lute",
        "a Flute",
        "a Drum",
        "a Trumpet",
        "a Violin",
        "a Cello",
        "a Harp",
        "a Piano",
        "an Organ",
        "an Accordion",
        "a Trombone",
        "a Tuba",
        "a French Horn",
        "a Clarinet",
        "an Oboe",
        "a Bassoon",
        "a Saxophone",
        "a Pen",
        "a Book",
        "a Key",
        "a Map",
        "a Compass",
        "a Watch",
        "a Clock",
        "a Calendar",
        "a Monicle",
        "Glasses",
        "Candy",
        "a Waterskin",
        "a Pennyfarthing",
        "a Thingamabob",
        "a Whatchamacallit",
        "a Plumbus"
    ],
    personNameRegistry: [
        { name: "Zeke", gender: "male" },
        { name: "Alexis", gender: "female" },
        { name: "Lincoln", gender: "male" },
        { name: "Victoria", gender: "female" },
        { name: "Lake", gender: "male" },
        { name: "Jane", gender: "female" },
        { name: "Ren", gender: "male" },
        { name: "Chris", gender: "male" },
        { name: "Helen", gender: "female" },
        { name: "Ysenia", gender: "female" },
        { name: "Drew", gender: "male" },
        { name: "Sam", gender: "male" },
        { name: "Molly", gender: "female" },
        { name: "Cailyn", gender: "female" },
        { name: "Tiffany", gender: "female" },
        { name: "Felix", gender: "male" },
        { name: "Warren", gender: "male" },
        { name: "Gabriel", gender: "male" },
        { name: "Miguel", gender: "male" },
        { name: "Fernanda", gender: "female" },
        { name: "Claire", gender: "female" },
        { name: "Allan", gender: "male" },
        { name: "Andres", gender: "male" },
        { name: "Will", gender: "male" },
        { name: "Rebecca", gender: "female" },
        { name: "Kaitlyn", gender: "female" },
        { name: "Lisa", gender: "female" },
        { name: "Mik", gender: "male" },
        { name: "Carola", gender: "female" },
        { name: "Jamila", gender: "female" },
        { name: "Jeanette", gender: "female" },
        { name: "Melissa", gender: "female" },
        { name: "Vince", gender: "male" },
        { name: "Brooke", gender: "female" },
        { name: "Trey", gender: "male" },
        { name: "Korey", gender: "male" },
        { name: "Lauren", gender: "male" },
        { name: "Mark", gender: "male" },
        { name: "John", gender: "male" },
        { name: "Sarah", gender: "female" },
        { name: "Jessica", gender: "female" },
        { name: "Martin", gender: "male" },
        { name: "David", gender: "male" },
        { name: "Michael", gender: "male" },
        { name: "Daniel", gender: "male" },
        { name: "Ashley", gender: "female" },
        { name: "Emily", gender: "female" },
        { name: "Amanda", gender: "female" },
        { name: "Megan", gender: "female" },
        { name: "Brittany", gender: "female" },
        { name: "Joshua", gender: "male" },
        { name: "Noah", gender: "male" },
        { name: "Asa", gender: "male" },
        { name: "Zach", gender: "male" },
        { name: "Roberto", gender: "male" },
        { name: "Aura", gender: "female" },
        { name: "Lily", gender: "female" },
        { name: "Alice", gender: "female" },
        { name: "Julia", gender: "female" },
        { name: "Meg", gender: "female" },
        { name: "Tess", gender: "female" },
        { name: "Sage", gender: "female" },
        { name: "Angela", gender: "female" },
        { name: "Bridget", gender: "female" },
        { name: "Jaime", gender: "female" },
        { name: "Joan", gender: "female" },
        { name: "Anne", gender: "female" },
        { name: "Jim", gender: "male" },
        { name: "Derek", gender: "male" },
        { name: "Alec", gender: "male" },
        { name: "Miles", gender: "male" },
        { name: "Adam", gender: "male" },
        { name: "Oscar", gender: "male" },
        { name: "Leo", gender: "male" },
        { name: "Oz", gender: "male" },
        { name: "Robert", gender: "male" },
        { name: "Adrian", gender: "male" },
        { name: "Conor", gender: "male" },
        { name: "Phil", gender: "male" },
        { name: "Dave", gender: "male" },
        { name: "Adrian", gender: "male" },
        { name: "Larry", gender: "male" },
        { name: "Paul", gender: "male" },
        { name: "Mike", gender: "male" },
        { name: "Frank", gender: "male" },
        { name: "Raymond", gender: "male" },
        { name: "Tony", gender: "male" },
        { name: "Hassan", gender: "male" },
        { name: "Abdul", gender: "male" },
        { name: "Jamal", gender: "male" },
        { name: "Ahmed", gender: "male" },
        { name: "Mohamed", gender: "male" },
        { name: "Sonal", gender: "female" },
        { name: "Fatima", gender: "female" },
        { name: "Jalle", gender: "female" },
    ],

    characterSkinRegistry: [
        // ── Type A (row 0) ── skins 0-25
        // Edit each gender field to 'male', 'female', or 'either'
        { row: 0, skin: 0, gender: 'either' },
        { row: 0, skin: 1, gender: 'male' },
        { row: 0, skin: 2, gender: 'either' },
        { row: 0, skin: 3, gender: 'female' },
        { row: 0, skin: 4, gender: 'either' },
        { row: 0, skin: 5, gender: 'either' },
        { row: 0, skin: 6, gender: 'male' },
        { row: 0, skin: 7, gender: 'male' },
        { row: 0, skin: 8, gender: 'male' },
        { row: 0, skin: 9, gender: 'either' },
        { row: 0, skin: 10, gender: 'either' },
        { row: 0, skin: 11, gender: 'male' },
        { row: 0, skin: 12, gender: 'either' },
        { row: 0, skin: 13, gender: 'male' },
        { row: 0, skin: 14, gender: 'male' },
        { row: 0, skin: 15, gender: 'male' },
        { row: 0, skin: 16, gender: 'male' },
        { row: 0, skin: 17, gender: 'male' },
        { row: 0, skin: 18, gender: 'male' },
        { row: 0, skin: 19, gender: 'male' },
        { row: 0, skin: 20, gender: 'either' },
        { row: 0, skin: 21, gender: 'either' },
        { row: 0, skin: 22, gender: 'either' },
        { row: 0, skin: 23, gender: 'either' },
        { row: 0, skin: 24, gender: 'either' },
        { row: 0, skin: 25, gender: 'either' },
        // ── Type B (row 12) ── skins 0-25
        { row: 12, skin: 0, gender: 'either' },
        { row: 12, skin: 1, gender: 'female' },
        { row: 12, skin: 2, gender: 'female' },
        { row: 12, skin: 3, gender: 'female' },
        { row: 12, skin: 4, gender: 'female' },
        { row: 12, skin: 5, gender: 'female' },
        { row: 12, skin: 6, gender: 'female' },
        { row: 12, skin: 7, gender: 'female' },
        { row: 12, skin: 8, gender: 'female' },
        { row: 12, skin: 9, gender: 'female' },
        { row: 12, skin: 10, gender: 'female' },
        { row: 12, skin: 11, gender: 'female' },
        { row: 12, skin: 12, gender: 'female' },
        { row: 12, skin: 13, gender: 'female' },
        { row: 12, skin: 14, gender: 'female' },
        { row: 12, skin: 15, gender: 'female' },
        { row: 12, skin: 16, gender: 'female' },
        { row: 12, skin: 17, gender: 'female' },
        { row: 12, skin: 18, gender: 'female' },
        { row: 12, skin: 19, gender: 'female' },
        { row: 12, skin: 20, gender: 'female' },
        { row: 12, skin: 21, gender: 'either' },
        { row: 12, skin: 22, gender: 'either' },
        { row: 12, skin: 23, gender: 'either' },
        { row: 12, skin: 24, gender: 'either' },
        { row: 12, skin: 25, gender: 'either' },
    ],
    townNameRegistry: [
        "Himfergen",
        "Walgon",
        "Sheeford",
        "Malpance",
        "Placington",
        "Townville",
        "Cityberg",
        "Villageton",
        "Littleburg",
        "Smallton",
        "Bigton",
        "Clockford"
    ],

};