export const gameConfig = {
    world: {
        width: 300,
        height: 300,
        tileSize: 32, // Size of a tile in pixels (for 2D) or units (for 3D)
        roomCount: 5,
        minionsPerTown: 1,
        townWidth: 40,
        townHeight: 40
    },
    playerProgression: {
        maxLevel: 10,
        xpCurve: [4, 8, 16, 32, 64, 128, 256, 512, 1024],
        stats: {
            strength: { base: 1, max: 5 },
            agility: { base: 1, max: 5 },  // Scales up velocity
            health: { base: 3, max: 10 },
            range: { base: 1, max: 5 }
        }
    },
    enemies: [
        {
            id: "slime",
            name: "Slime",
            hp: 2,
            xp: 1,
            speed: 1.0,
            max: 15,
            toKill: 5
        },
        {
            id: "mushroom",
            name: "Mushroom",
            hp: 3,
            xp: 1,
            speed: 3.0,
            max: 20,
            toKill: 4
        },
        {
            id: "snake",
            name: "Snake",
            hp: 4,
            xp: 2,
            speed: 3.5,
            max: 20,
            toKill: 3
        },
        {
            id: "druid",
            name: "Wizard",
            hp: 5,
            xp: 3,
            speed: 1.5,
            max: 10,
            toKill: 2
        },
        {
            id: "skeleton",
            name: "Skeleton",
            hp: 6,
            xp: 6,
            speed: 2.0,
            max: 10,
            toKill: 2
        },
        {
            id: "dude",
            name: "Dude Bandit",
            hp: 7,
            xp: 4,
            speed: 6.0,
            max: 10,
            toKill: 3
        },
        {
            id: "chick",
            name: "Lady Bandit",
            hp: 7,
            xp: 4,
            speed: 6.0,
            max: 10,
            toKill: 4
        },
        {
            id: "soldier",
            name: "Undead Knight",
            hp: 20,
            xp: 15,
            speed: 8,
            max: 5,
            toKill: 1
        }
    ],
    itemNameRegistry: [
        "Sword",
        "Shield",
        "Axe",
        "Bow",
        "Staff",
        "Potion",
        "Scroll",
        "Ring",
        "Helmet",
        "Boots",
        "Gloves",
        "Shoes",
        "Cloak",
        "Amulet",
        "Bracers",
        "Greaves",
        "Gauntlets",
        "Hat",
        "Cape",
        "Robe",
        "Spoon",
        "Fork",
        "Knife",
        "Mug",
        "Goblet",
        "Cup",
        "Plate",
        "Bowl",
        "Laddle",
        "Pan",
        "Guitar",
        "Lute",
        "Flute",
        "Drum",
        "Trumpet",
        "Violin",
        "Cello",
        "Harp",
        "Piano",
        "Organ",
        "Accordion",
        "Trombone",
        "Tuba",
        "French Horn",
        "Clarinet",
        "Oboe",
        "Bassoon",
        "Saxophone",
        "Pen",
        "Book",
        "Key",
        "Map",
        "Compass",
        "Watch",
        "Clock",
        "Calendar",
        "Monicle",
        "Glasses",
        "Candy",
        "Waterskin",
        "Pennyfarthing",
        "Thingamabob",
        "Whatchamacallit",
        "Plumbus"
    ],
    personNameRegistry: [
        { name: "Zeke", gender: "male" },
        { name: "Alexis", gender: "female" },
        { name: "Lincoln", gender: "male" },
        { name: "Victoria", gender: "female" },
        { name: "Lake", gender: "male" },
        { name: "Jane", gender: "female" },
        { name: "Ren", gender: "male" },
        { name: "Chris", gender: "male" },
        { name: "Helen", gender: "female" },
        { name: "Ysenia", gender: "female" },
        { name: "Drew", gender: "male" },
        { name: "Sam", gender: "male" },
        { name: "Molly", gender: "female" },
        { name: "Cailyn", gender: "female" },
        { name: "Tiffany", gender: "female" },
        { name: "Felix", gender: "male" },
        { name: "Warren", gender: "male" },
        { name: "Gabriel", gender: "male" },
        { name: "Miguel", gender: "male" },
        { name: "Fernanda", gender: "female" },
        { name: "Claire", gender: "female" },
        { name: "Allan", gender: "male" },
        { name: "Andres", gender: "male" },
        { name: "Will", gender: "male" },
        { name: "Rebecca", gender: "female" },
        { name: "Kaitlyn", gender: "female" },
        { name: "Lisa", gender: "female" },
        { name: "Mik", gender: "male" },
        { name: "Carola", gender: "female" },
        { name: "Jamila", gender: "female" },
        { name: "Jeanette", gender: "female" },
        { name: "Melissa", gender: "female" },
        { name: "Vince", gender: "male" },
        { name: "Brooke", gender: "female" },
        { name: "Trey", gender: "male" },
        { name: "Korey", gender: "male" },
        { name: "Lauren", gender: "male" },
        { name: "Mark", gender: "male" },
        { name: "John", gender: "male" },
        { name: "Sarah", gender: "female" },
        { name: "Jessica", gender: "female" },
        { name: "Martin", gender: "male" },
        { name: "David", gender: "male" },
        { name: "Michael", gender: "male" },
        { name: "Daniel", gender: "male" },
        { name: "Ashley", gender: "female" },
        { name: "Emily", gender: "female" },
        { name: "Amanda", gender: "female" },
        { name: "Megan", gender: "female" },
        { name: "Brittany", gender: "female" },
        { name: "Joshua", gender: "male" },
        { name: "Noah", gender: "male" },
        { name: "Asa", gender: "male" },
    ],
    townNameRegistry: [
        "Himfergen",
        "Walgon",
        "Sheeford",
        "Malpance",
        "Placington",
        "Townville",
        "Cityberg",
        "Villageton",
        "Littleburg",
        "Smallford",
        "Bigton",
        "Clockford"
    ],

};